/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as KidRouteImport } from './routes/kid'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KidTasksRouteImport } from './routes/kid.tasks'
import { Route as KidScannerRouteImport } from './routes/kid.scanner'
import { Route as KidRewardsRouteImport } from './routes/kid.rewards'
import { Route as KidQuizRouteImport } from './routes/kid.quiz'
import { Route as KidInvestRouteImport } from './routes/kid.invest'
import { Route as KidGameRouteImport } from './routes/kid.game'

const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const KidRoute = KidRouteImport.update({
  id: '/kid',
  path: '/kid',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KidTasksRoute = KidTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => KidRoute,
} as any)
const KidScannerRoute = KidScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => KidRoute,
} as any)
const KidRewardsRoute = KidRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => KidRoute,
} as any)
const KidQuizRoute = KidQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => KidRoute,
} as any)
const KidInvestRoute = KidInvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => KidRoute,
} as any)
const KidGameRoute = KidGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => KidRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kid': typeof KidRouteWithChildren
  '/parent': typeof ParentRoute
  '/kid/game': typeof KidGameRoute
  '/kid/invest': typeof KidInvestRoute
  '/kid/quiz': typeof KidQuizRoute
  '/kid/rewards': typeof KidRewardsRoute
  '/kid/scanner': typeof KidScannerRoute
  '/kid/tasks': typeof KidTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kid': typeof KidRouteWithChildren
  '/parent': typeof ParentRoute
  '/kid/game': typeof KidGameRoute
  '/kid/invest': typeof KidInvestRoute
  '/kid/quiz': typeof KidQuizRoute
  '/kid/rewards': typeof KidRewardsRoute
  '/kid/scanner': typeof KidScannerRoute
  '/kid/tasks': typeof KidTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kid': typeof KidRouteWithChildren
  '/parent': typeof ParentRoute
  '/kid/game': typeof KidGameRoute
  '/kid/invest': typeof KidInvestRoute
  '/kid/quiz': typeof KidQuizRoute
  '/kid/rewards': typeof KidRewardsRoute
  '/kid/scanner': typeof KidScannerRoute
  '/kid/tasks': typeof KidTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kid'
    | '/parent'
    | '/kid/game'
    | '/kid/invest'
    | '/kid/quiz'
    | '/kid/rewards'
    | '/kid/scanner'
    | '/kid/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kid'
    | '/parent'
    | '/kid/game'
    | '/kid/invest'
    | '/kid/quiz'
    | '/kid/rewards'
    | '/kid/scanner'
    | '/kid/tasks'
  id:
    | '__root__'
    | '/'
    | '/kid'
    | '/parent'
    | '/kid/game'
    | '/kid/invest'
    | '/kid/quiz'
    | '/kid/rewards'
    | '/kid/scanner'
    | '/kid/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KidRoute: typeof KidRouteWithChildren
  ParentRoute: typeof ParentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kid': {
      id: '/kid'
      path: '/kid'
      fullPath: '/kid'
      preLoaderRoute: typeof KidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kid/tasks': {
      id: '/kid/tasks'
      path: '/tasks'
      fullPath: '/kid/tasks'
      preLoaderRoute: typeof KidTasksRouteImport
      parentRoute: typeof KidRoute
    }
    '/kid/scanner': {
      id: '/kid/scanner'
      path: '/scanner'
      fullPath: '/kid/scanner'
      preLoaderRoute: typeof KidScannerRouteImport
      parentRoute: typeof KidRoute
    }
    '/kid/rewards': {
      id: '/kid/rewards'
      path: '/rewards'
      fullPath: '/kid/rewards'
      preLoaderRoute: typeof KidRewardsRouteImport
      parentRoute: typeof KidRoute
    }
    '/kid/quiz': {
      id: '/kid/quiz'
      path: '/quiz'
      fullPath: '/kid/quiz'
      preLoaderRoute: typeof KidQuizRouteImport
      parentRoute: typeof KidRoute
    }
    '/kid/invest': {
      id: '/kid/invest'
      path: '/invest'
      fullPath: '/kid/invest'
      preLoaderRoute: typeof KidInvestRouteImport
      parentRoute: typeof KidRoute
    }
    '/kid/game': {
      id: '/kid/game'
      path: '/game'
      fullPath: '/kid/game'
      preLoaderRoute: typeof KidGameRouteImport
      parentRoute: typeof KidRoute
    }
  }
}

interface KidRouteChildren {
  KidGameRoute: typeof KidGameRoute
  KidInvestRoute: typeof KidInvestRoute
  KidQuizRoute: typeof KidQuizRoute
  KidRewardsRoute: typeof KidRewardsRoute
  KidScannerRoute: typeof KidScannerRoute
  KidTasksRoute: typeof KidTasksRoute
}

const KidRouteChildren: KidRouteChildren = {
  KidGameRoute: KidGameRoute,
  KidInvestRoute: KidInvestRoute,
  KidQuizRoute: KidQuizRoute,
  KidRewardsRoute: KidRewardsRoute,
  KidScannerRoute: KidScannerRoute,
  KidTasksRoute: KidTasksRoute,
}

const KidRouteWithChildren = KidRoute._addFileChildren(KidRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KidRoute: KidRouteWithChildren,
  ParentRoute: ParentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
